default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: postgres
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: exchange_development

test:
  <<: *default
  database: exchange_test

production:
  <<: *default
  database: exchange_production
